// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240502112828_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy Spark",
                            CategoryId = 3,
                            Description = "Lorem Ipsum",
                            ISBN = "Ikj32728",
                            ImageUrl = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 20.0,
                            Price50 = -35.0,
                            Title = "Fortune of time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Willy Wonka",
                            CategoryId = 2,
                            Description = "Lorem Ipsum",
                            ISBN = "Mus53720",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Price = 70.0,
                            Price100 = 30.0,
                            Price50 = -15.0,
                            Title = "Dark Skies"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Billy Spark",
                            CategoryId = 1,
                            Description = "Lorem Ipsum",
                            ISBN = "Ikj32728",
                            ImageUrl = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 20.0,
                            Price50 = -35.0,
                            Title = "Fortune of time"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Willy Wonka",
                            CategoryId = 3,
                            Description = "Lorem Ipsum",
                            ISBN = "Mus53720",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Price = 70.0,
                            Price100 = 30.0,
                            Price50 = -15.0,
                            Title = "Dark Skies"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Billy Spark",
                            CategoryId = 2,
                            Description = "Lorem Ipsum",
                            ISBN = "Ikj32728",
                            ImageUrl = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 20.0,
                            Price50 = -35.0,
                            Title = "Fortune of time"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Willy Wonka",
                            CategoryId = 1,
                            Description = "Lorem Ipsum",
                            ISBN = "Mus53720",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Price = 70.0,
                            Price100 = 30.0,
                            Price50 = -15.0,
                            Title = "Dark Skies"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Billy Spark",
                            CategoryId = 3,
                            Description = "Lorem Ipsum",
                            ISBN = "Ikj32728",
                            ImageUrl = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 20.0,
                            Price50 = -35.0,
                            Title = "Fortune of time"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
